### ISSUE TITLE
Web Service sudah expired.

### ISSUE THREAD

**Issue by Daiku88** [virbo/wsfeeder#1]
Web Service sudah expired. Silakan lakukan update web service atau hubungi tanya.dikti.go.id
ini kenapa mas.?? mohon dibantu ya :)

**Comment by virbo** [comment]
silahkan update webservice melalui menu setting->sandbox di aplikasi feeder

**Comment by Daiku88** [comment]
di sistem PDDIKTI nya atau di sistem ws feddernya mas update webservernya?

**Comment by virbo** [comment]
di PDDIKTI Feeder pak...caranya login ke feeder, kemudian klik menu Setting-->Sandbox...nanti dihalaman itu ada tombol Update Aplikasi Web Service..klik tombol ini untuk mengupdate webservice

**Comment by andrekarnyoto** [comment]
mohon maaf, tetapi dalam menu feeder nya gak ada setting -->sandbox, yang ada hanya seperti dibawah ini 

![sanboxdikit](https://cloud.githubusercontent.com/assets/9191830/9458686/f2a9e762-4b23-11e5-908c-23869a415bad.jpg)

**Comment by virbo** [comment]
itu loginnya pake user admin PT atau admin Prodi?? kalau loginnya menggunakan Admin PT, menu yang tampak mestinya spt gambar ini...
jika anda tidak memiliki hak akses terhadap Admin Prodi, sebaiknya minta tolong kepada rekannya yang memiliki hak akses tersebut untuk meng-update-kan webservice feeder-nya...
![ss_update_ws](https://cloud.githubusercontent.com/assets/2990842/9466891/84b8ee5a-4b6a-11e5-98ac-45db5f4e6e59.jpg)

**Comment by gudang** [comment]
@virbo  sudah diupdate webservicenya tetap saja seperti gambar dibawah ini mas
![11903263_10203397785865191_1396340190_o](https://cloud.githubusercontent.com/assets/8652780/9487662/f64d483e-4bfd-11e5-9c6b-e41a43593a86.jpg)

EDIT: udah bisa ternyata mas, setting alamat web feeder di file epsbed.ini dulu ternata :smile:

**Comment by jefrip** [comment]
Halo mas @virbo saya juga mengalami hal yang sama, padahal sudah update ke Patch PD DIKTI v1.1 rev d #20150623.
mas @gudang : update alamat web feeder bagaimana jdnya ya?

EDIT: saya sudah update Webservice seperti mas @virbo bilang, hanya saja harus buka akses port 80 ke luar, sebelumnya tidak bs karena belum dibuka. saya kira mungkin sertakan update WS lewat update zip yang biasa disediakan. terima kasih.

**Comment by virbo** [comment]
mas @gudang, setelah update webservice logout terlebih dahulu setelah itu login kembali...
mas @jefrip, maksudnya spt apa ya?? webservice diupdate via feeder..

**Comment by dedywong31** [comment]
mas @virbo, punya saya juga sama kasusnya, muncul pesan "Web Service sudah expired. Silakan lakukan update web service atau hubungi tanya.dikti.go.id". Saya sudah ikutin saran dari mas, saya update web servicenya dari feeder dan logout kemudian login lagi. tetapi masih belum bisa. Harap bantuannya mas. Terima kasih

**Comment by virbo** [comment]
mas @Starlight31, mestinya setelah update webservice via feeder, masalah ini akan selesai...saya tidak tahu yg mas update itu apakah webservice-nya atau feeder-nya...karena di feeder itu ada juga menu untuk update feeder...pastikan langkah update webservice yg mas @Starlight31 lakukan sama spt ini https://github.com/virbo/wsfeeder/issues/1#issuecomment-134573857

**Comment by dedywong31** [comment]
mas @virbo , saya sudah ikuti langkah #1, tetapi masih belum berhasil. 
terus setting alamat web feeder di file epsbed.ini itu seprti gimana ya ?
harap infonya. terima kasih

**Comment by virbo** [comment]
mas @Starlight31, jika memang webservice sudah diupdate sesuai dengan petunjuk ini https://github.com/virbo/wsfeeder/issues/1 maka seharusnya webservice sdh bisa digunakan...untuk settingan file epsbed.ini urutannya yang pertama setting folder EPSBED, dan yg kedua tanda pemisah yaitu tanda pagar (#) kemudian yg terakhir settingan alamat webservice feeder...contoh: **C:\DIKTI#http://localhost:8082/ws/**

**Comment by tommyiraone** [comment]
Aplikasi web service gagal diupdate. Hubungi Administrator bila masalah bukan karena koneksi internet.

Artinya apa ya mas ??

**Comment by Gudmojo46** [comment]
Mas, untuk import data bagaimana ya? sampai saat ini saya belum berhasil mencobanya. selalu gagal. tidak ada kah contoh excel/csv pengisian data yang benarnya?
