### ISSUE TITLE
Tidak bisa insert / upload csv mahasiswa

### ISSUE THREAD

**Issue by Itoel** [virbo/wsfeeder#2]
Mengapa tidak bisa insert mahasiswa bang, muncul error seperti ini

ERROR SQL ERROR: current transaction is aborted, commands ignored until end of transaction block

**Comment by supantara** [comment]
Isi data csv sesuai dengan format aja, saya sudah coba. Dan hasilnya
berhasil import data mhs, nilai semester dan akm. Tapi belum ada menu
import daftar mhs lulus/do, sehingga lulusan/mhs keluar harus diinput dari
feeder.
Pada tanggal 28 Agt 2015 20.54, "Itoel" notifications@github.com menulis:

**Comment by virbo** [comment]
mas @Itoel, error **ERROR SQL ERROR: current transaction is aborted, commands ignored until end of transaction block** kurang lebih disebabkan oleh kagagalan dari sistem webservice feeder dalam eksekusi perintah insert ke database...untuk percobaan awal, coba lakukan update webservice via menu Setting-->Sandbox di aplikasi feeder

**Comment by hariste** [comment]
mas @virbo, saya juga mengalami error yang sama dengan mas @Itoel . Waktu  memasukkan data mahasiswa, kena error ERROR SQL ERROR: current transaction is aborted, commands ignored until end of transaction block. 

Sudah melakukan update webservice juga via menu Setting-Sandbox, akan tetapi hasilnya masih sama saja.

**Comment by jefrip** [comment]
mas @virbo maksimal jumlah record dlm upload brp record ya mas?soalnya saya upload gagal terus

terima kasih.

**Comment by virbo** [comment]
untuk pastinya jumlah record dalam sekali upload saya tdk tau pastinya brapa...tapi yang pernah saya uji coba-kan sekitar 200-an data masih bisa dihandle...btw gagalnya spt apa mas @jefrip ??

**Comment by supantara** [comment]
@virbo masimal limit import data mhsnya berapa ya? saya sempat coba import 900 tapi data yang masuk cuma sebagian (300an) dan bisa ditambahkan menu lagi gak untuk import daftar mahasiswa lulus/do dan import krs.
maaf saya banyak nanya. makasi hasil karyanya sangat membantu.

**Comment by virbo** [comment]
untuk angka pastinya saya tidak tau, karena semuanya bisa saja tergantung dari kecepatan proses data di masing2 PC. sebagai contoh, tadi siang saya berhasil import data AKM sebanyak 3000an data sekaligus.. dan seharusnya untuk import data mhs bisa dilakukan lebih dari 3000an data sekali upload..ini dikarenakan pada saat upload data mhs proses yg terjadi hanya satu yaitu proses insert. ini berbeda ketika import data AKM, proses yg terjadi ada dua proses yaitu proses pencarian dan kemudian proses insert.  @supantara

**Comment by hendrahe2885** [comment]
ERROR SQL ERROR: current transaction is aborted, commands ignored until end of transaction block (Fitrina Armalia / 1996-02-19)
gan, ini disebabkan apa karena sudah mencoba diupdate web service tp tetap muncul seperti ini.

**Comment by henry-h** [comment]
ERROR SQL ERROR: current transaction is aborted, commands ignored until end of transaction block (Daniel / 1997-03-03) 

web service sudah diupdate, 
saya coba langsung dari php 
$result = $_ws->proxy->InsertRecord($_ws->token, 'mahasiswa', json_encode($record));
sama juga.
Saya beri contoh datanya, apakah ada yang salah/kurang? 
    [nm_pd] => Daniel
    [jk] => L
    [tmpt_lahir] => Bandung
    [tgl_lahir] => 1997-03-03
    [id_agama] => 2
    [id_kk] => 0
    [id_sp] => 639dc79c-c840-4fe9-bf46-037b953e2d54
    [jln] => Babakan Ciparay
    [ds_kel] => kelurahan
    [id_wil] => 000000
    [kode_pos] => 40293
    [id_jns_tinggal] => 0
    [telepon_rumah] => 0229035481
    [telepon_seluler] => 08996923515
    [email] => gaunlet1@gmail.com
    [a_terima_kps] => 0
    [stat_pd] => A
    [nm_ayah] => Rudi Sadikin
    [id_jenjang_pendidikan_ayah] => 99
    [id_pekerjaan_ayah] => 99
    [id_penghasilan_ayah] => 16
    [id_kebutuhan_khusus_ayah] => 0
    [nm_ibu_kandung] => Ibu
    [id_jenjang_pendidikan_ibu] => 99
    [id_penghasilan_ibu] => 16
    [id_pekerjaan_ibu] => 99
    [id_kebutuhan_khusus_ibu] => 0
    [kewarganegaraan] => ID
    [regpd_id_sms] => 2e159bd6-6571-4185-aeba-6gte570d60d9
    [regpd_id_sp] => 639dc79c-c840-4fe9-bf46-037b953e2d54
    [regpd_id_jns_daftar] => 1
    [regpd_nipd] => 1115111
    [regpd_tgl_masuk_sp] => 2014-10-14
    [regpd_mulai_smt] => 20151

Output $result :
Array
(
    [error_code] => 0
    [error_desc] => 
    [result] => Array
        (
            [nm_pd] => Daniel
            [tgl_lahir] => 1997-03-03
            [nisn] => 
            [regpd_nipd] => 
            [error_code] => 103
            [error_desc] => ERROR SQL ERROR:  current transaction is aborted, commands ignored until end of transaction block
        )

)

UPDATE:
Ternyata error hanya terjadi di mode SANDBOX di mode LIVE sukses data masuk.

**Comment by hendrahe2885** [comment]
Saya sudah coba menggunakan mode LIVE maupun SANDBOX tapi tetap error.

**Comment by imamzaenuddin** [comment]
Iya masih error,masalahnya kenapa ya. mohon bantuan Gan

**Comment by hendrahe2885** [comment]
saya udah pake wsfeeder mas alim om.Download disini http://www.alimsumarno.com/webservice/default.Asp

**Comment by imamzaenuddin** [comment]
Ta Coba ah..

**Comment by boedyirh** [comment]
Sepertinya struktur web service dikti, sudah diupdate. Sehingga sepertinya scriptnya perlu dimodifikasi menyesuaikan.

**Comment by virbo** [comment]
betul om @boedyirh ...tpi yg berubah itu sejauh ini hanya ada di tabel mahasiswa dan mahasiswa_pt...sedangkan untuk tabel yg lain nyaris tidak ada perubahan sama sekali...karena perubahan adanya di tabel mahasiswa, maka untuk script insert data mahasiswa yang ada di github ini menjadi tidak bisa digunakan untuk import mahasiswa..kedepannya, insya allah script yang ada di github ini akan sya update...untuk sementara bisa gunakan wsclient versi 2 yang bisa di download di http://wsclient.jago.link

**Comment by boedyirh** [comment]
Terima kasih Pak Yusuf. Sangat sangat membantu sekali. :+1:

**Comment by gedank** [comment]
selamat sore,
saya sedang membuat singkronisasi siakad dengan feeder dikti, saat menambah data mahasiswa baru data tidak bisa masuk ke feeder dan muncul error seperti ini
Array ( [error_code] => 0 [error_desc] => [result] => Array ( [error_code] => 103 [error_desc] => ERROR SQL ERROR: new row for relation "peserta_didik" violates check constraint "ckc_stat_pd_peserta_" DETAIL: Failing row contains (8abb5885-8f1a-4582-94ee-44f793bced30, hesti wahyu nugroho, L, 1 , 1 , semarang, 2015-12-04, 1, 1, 529fc7d4-1d81-4145-bb34-8c7fc89bf250, a, 1, 2, a, a, 1 , 55555, 1, 1, 123213123, 323131, a@a.com, 1, 1, 1, 1, 2015-12-17, 1, 1, 1, 0, 1, 2015-12-10, 1, 1, 1, 0, a, 2015-12-02, 1, 1, 1, ID, 1901-01-01 00:30:00, 0, 1901-01-01 00:00:00, 4e68b9cf-b451-4598-9960-03cf1c5f2b3b). ) )
mohon bantuannya,
terima kasih

**Comment by sopingi** [comment]
saya juga punya eror yang sama dengan mas @gedank 

[error_code] => 103
                    [error_desc] => ERROR SQL ERROR:  new row for relation "peserta_didik" violates check constraint "ckc_stat_pd_peserta_"
DETAIL:  Failing row contains (620f653c-1fb0-40ac-8c6c-391440173ecb, DEBI AYUDITASARI, P,           , 33              , Wonogiri, 1997-07-02, 1, 0, dea50385-fb50-4d4b-b50c-dbc539da3292, -, 1, 8, Tulakan, Waleng, 031224  , -    , 1, 0, -, 082242967057, debiayudita@gmail.com, 0, ,  , , 2015-12-23, 0, 0, 0, 0, Sutarni, 2015-12-23, 0, 0, 0, 0, , 1111-11-11, 0, 0, 0, ID, 1901-01-01 00:30:00, 0, 1901-01-01 00:00:00, 832c9496-4ed3-4c5e-88d5-c40e3cfdf5ae).

**Comment by gedank** [comment]
@sopingi,
Itu bisa mas, coba dicheck lagi data yg di insert,
Format harus sesuai dengan feeder, untuk kolom yg berelasi isinya harus sesuai dengan id relasi, terus format tgl tidak boleh 0000-00-00, harus ada isinya 1945-08-17,
Semoga bermanfaat
